% see Bruus, H. Theoretical Microfluidics 2006
function vxMS = flowProfileRectangularTubeParabolicTopMS(widthM, heightCenterM,heightSlope,heightCurvatureM,yM,zM,flowRateM3S)
    lengthM=1;
    dynamicViscosityPaS=1;
    
    l=Logger.getInstance();
    heffM=getHEff(heightCenterM,heightSlope,heightCurvatureM,widthM);
    
    hRealM=heightCenterM+heightSlope.*yM+heightCurvatureM.*yM.^2;
    l.warn('Center: ',heightCenterM,...
           '  Heff: ', heffM,...
           '  hRealM: ',hRealM);
    pressureDifferencePa=flowResistanceRectangularTubePaSM3(widthM,heffM,lengthM,dynamicViscosityPaS).*flowRateM3S;
    vxMS=(4.*hRealM.^2.*pressureDifferencePa)./(pi.^3.*dynamicViscosityPaS.*lengthM).*getAlphaRect(widthM, hRealM, yM,zM);
end

% (integral_(-w/2)^(w/2) 1/w (a+bx+cx^2)^3 dx)^(1/3)
function heff=getHEff(heigthCenter,slope,curvatureM,widthM)
    heff=(...
            1./widthM.*( ...
                 heigthCenter.^3*widthM+...
                 1./4.*heigthCenter^2*curvatureM*widthM^3+...
                 1./4.*heigthCenter.*slope^2.*widthM^3+...
                 3./80.*heigthCenter.*curvatureM.^2.*widthM.^5+...
                 3./80.*slope.^2.*curvatureM.*widthM.^5+...
                 1./448.*curvatureM.^3.*widthM.^7 ...
            ) ...
         ).^(1./3);
end