%% ##Header##
clear;
clc;
l=Logger.getInstance();
l.setCommandWindowLevel(Logger.INFO);

%% ## Bead Specification ##
% BEAD_TYPES={
%     'micromodNH2_50pN(.+)',...
%     'micromodNH2_100pN(.+)',...
%     'micromodNH2_150pN(.+)',...
%     'micromodNH2_200pN(.+)',...
%     'micromodNH2_250pN(.+)',...
%     'micromodNH2_300pN(.+)',...
%     'micromodNH2_800pN(.+)',...
%     'micromodNR3_100pN(.+)',...
%     'micromodNR3_150pN(.+)',...
%     'micromodNR3_200pN(.+)',...
%     'micromodNR3_300pN(.+)',...
%     'micromodNR3_400pN(.+)',...
%     'micromodNR3_500pN(.+)',...
%     'micromodNR3_600pN(.+)',...
%     'micromodNR3_800pN(.+)'};
% NAME='';
% BEAD_TYPES={'polyscienceCOOH(.+)_0min',...
%     'polyscienceCOOH(.+)_40min',...
%     'polyscienceCOOH(.+)_80min',...
%     'micromodCOOH(.+)_0min',...
%     'micromodCOOH(.+)_40min',...
%     'micromodCOOH(.+)_80min',...
%     'spherotechNH2(.+)_0min',...
%     'spherotechNH2(.+)_40min',...
%     'spherotechNH2(.+)_80min',...
%     'micromodNH2(.+)_0min',...
%     'micromodNH2(.+)_40min',...
%     'micromodNH2(.+)_80min',...
%     'polyscienceNH2(.+)_0min',...
%     'polyscienceNH2(.+)_40min',...
%     'polyscienceNH2(.+)_80min',...
%     'micromodNR3(.+)_0min',...
%     'micromodNR3(.+)_40min',...
%     'micromodNR3(.+)_80min'};
% NAME='';
% 
% BEAD_TYPES={'polyscienceCOOH(.+)',...
%     'micromodCOOH(.+)',...
%     'spherotechNH2(.+)',...
%     'micromodNH2(.+)',...
%     'polyscienceNH2(.+)',...
%     'micromodNR3(.+)'};
% NAME='';


BEAD_TYPES={'MMC','MMplain'};
NAME='';
% 
% BEAD_TYPES={'polyscienceCOOH(.+)_0min',...
%     'polyscienceCOOH(.+)_40min',...
%     'polyscienceCOOH(.+)_80min',...
%     'polyscienceNH2(.+)_0min',...
%     'polyscienceNH2(.+)_40min',...
%     'polyscienceNH2(.+)_80min'};
% NAME='';


% BEAD_TYPES={'micromodPLAIN'};%,...
%     'AGED_SW',...
%     'AGED_FW',...
%     'PLAIN_UW',...
%     'PLAIN_SW',...
%     'PLAIN_FW'};
% NAME='';
%
% BEAD_TYPES={'mf030_simon_.*KiskerPlain.*Channel4_01',...
%             'mf030_simon_.*KiskerPlain.*Channel4_02',...
%             'mf030_simon_.*KiskerPlain.*Channel4_03',...
%             'mf030_simon_.*KiskerPlain.*Channel5_01',...
%             'mf030_simon_.*KiskerPlain.*Channel5_02',...
%             'mf030_simon_.*KiskerPlain.*Channel6_01',...
%             'mf030_simon_.*KiskerPlain.*Channel6_02',...
%             'mf030_simon_.*KiskerPlain.*Channel6_03'};
% NAME='KiskerPlain';
% 
% BEAD_TYPES={'mf031_simon_.*Micropar.*Plain_50pN_Channel1_01',...
%             'mf031_simon_.*Micropar.*Plain_50pN_Channel1_02',...
%             'mf031_simon_.*Micropar.*Plain_50pN_Channel2_01',...
%             'mf031_simon_.*Micropar.*Plain_50pN_Channel2_02',...
%             'mf031_simon_.*Micropar.*Plain_50pN_Channel3_01',...
%             'mf031_simon_.*Micropar.*Plain_50pN_Channel3_02',...
%             'mf035_simon_.*Micropar.*Plain_50pN_Channel1_01',...
%             'mf035_simon_.*Micropar.*Plain_50pN_Channel2_01'};
% NAME='MicroparticlesPlain';
%         
% BEAD_TYPES={'mf033_simon_.*MicromodCOOH.*Channel10_01',...
%             'mf033_simon_.*MicromodCOOH.*Channel11_01',...
%             'mf033_simon_.*MicromodCOOH.*Channel12_01'};
% NAME='MicromodCOOH';
% 
% BEAD_TYPES={'mf030_simon_.*MicromodPlain.*Channel1_01',...
%             'mf030_simon_.*MicromodPlain.*Channel1_02',...
%             'mf030_simon_.*MicromodPlain.*Channel2_01',...
%             'mf030_simon_.*MicromodPlain.*Channel2_02',...
%             'mf030_simon_.*MicromodPlain.*Channel2_03',...
%             'mf030_simon_.*MicromodPlain.*Channel2_04',...
%             'mf030_simon_.*MicromodPlain.*Channel3_01',...
%             'mf030_simon_.*MicromodPlain.*Channel3_02',...
%             'mf030_simon_.*MicromodPlain.*Channel3_03'};
% NAME='MicromodPlain';
% 
% BEAD_TYPES={'mf032_simon_.*Phosphor.*Plain_50pN_Channel4_01',...
%             'mf032_simon_.*Phosphor.*Plain_50pN_Channel4_02',...
%             'mf032_simon_.*Phosphor.*Plain_50pN_Channel5_01',...
%             'mf032_simon_.*Phosphor.*Plain_50pN_Channel6_01',...
%             'mf032_simon_.*Phosphor.*Plain_50pN_Channel6_02',...
%             'mf032_simon_.*Phosphor.*Plain_50pN_Channel6_03',...
%             'mf034_simon_.*Phosphor.*Plain_50pN_Channel1_01',...
%             'mf034_simon_.*Phosphor.*Plain_50pN_Channel1_02',...
%             'mf034_simon_.*Phosphor.*Plain_50pN_Channel2_01',...
%             'mf034_simon_.*Phosphor.*Plain_50pN_Channel2_02',...
%             'mf034_simon_.*Phosphor.*Plain_50pN_Channel3_01'};
% NAME='PhosphorexPlain';
% 
% BEAD_TYPES={'mf033_simon_.*PolyscienceCOOH.*Channel4_01',...
%             'mf033_simon_.*PolyscienceCOOH.*Channel5_01',...
%             'mf033_simon_.*PolyscienceCOOH.*Channel6_01'};
% NAME='PolyscienceCOOH';
% 
% BEAD_TYPES={'mf033_simon_.*PolyscienceNH2.*Channel7_01',...
%             'mf033_simon_.*PolyscienceNH2.*Channel8_01'};
%             %##'mf033_simon_.*PolyscienceNH2.*Channel9_01'};
% NAME='PolyscienceNH2';
%             
% BEAD_TYPES={'mf033_simon_.*PolysciencePlain_50pN_Channel1_01',...
%             'mf033_simon_.*PolysciencePlain_50pN_Channel2_01',...
%             'mf033_simon_.*PolysciencePlain_50pN_Channel3_01'};
% NAME='PolysciencePlain';
%         
% BEAD_TYPES={'mf032_simon_.*SpherotechPlain.*Channel1_01',...
%             'mf032_simon_.*SpherotechPlain.*Channel2_01',...
%             'mf032_simon_.*SpherotechPlain.*Channel3_01'};
% NAME='SphereotechPlain';
%         
% BEAD_TYPES={'mf031_simon_.*ThermoSc.*Plain_50pN_Channel4_01',...
%             'mf031_simon_.*ThermoSc.*Plain_50pN_Channel5_01',...
%             'mf031_simon_.*ThermoSc.*Plain_50pN_Channel6_01',...
%             'mf034_simon_.*ThermoSc.*Plain_50pN_Channel4_01',...
%             'mf034_simon_.*ThermoSc.*Plain_50pN_Channel5_01',...
%             'mf034_simon_.*ThermoSc.*Plain_50pN_Channel6_01'};
% NAME='ThermoScientificPlain';
% 
% BEAD_TYPES={'mf032_simon_.*TianJinPlain.*Channel8_01',...
%             'mf032_simon_.*TianJinPlain.*Channel9_01',...
%             'mf032_simon_.*TianJinPlain.*Channel10_01',...
%             'mf035_simon_.*TianjinPlain.*Channel4_01',...
%             'mf036_simon_.*TianjinPlain.*Channel2_01',...
%             'mf036_simon_.*TianjinPlain.*Channel3_01',...
%             'mf036_simon_.*TianjinPlain.*Channel1_01'};
% NAME='TianjinPlain';


%% #### BASIC SETUP ####
OVERVIEW=isempty(NAME);
COLORS=[166,206,227;...
        31,120,180;...
        178,223,138;...
        51,160,44;...
        251,154,153;...
        227,26,28;...
        253,191,111;...
        255,127,0;...
        202,178,214;...
        106,61,154;...
        255,255,153;...
        0 0 0;...
        204 0 102;...
        255 102 255;...
        0 0 153;...
        160 160 160;
        102 255 178;...
        51 255 51]./255;
    
COLORS=COLORS(1:size(BEAD_TYPES,2),:);

%% #### CALCULATION ####
sas=SedimentationAnalysisSummary(BEAD_TYPES,200); %Immobilized threshold = 200;

%% #### PLOTTING ####
figure(15);
clf;
set(gcf,'Position',[56,131,1308,792]);
ax(1)=subplot(1,2,1);
title('on cells');
xlabel('time after sedimentation / s');
ylabel('rel fixed count');
ylim([0,1]);
xlim(ax(1),[0,550]);

ax(2)=subplot(1,2,2);
title('on coverslips');
ylabel('rel fixed count');
xlabel('time after sedimentation / s');
ylim([0,1]);
xlim(ax(2),[0,550]);

hold(ax(1),'on');
hold(ax(2),'on');


relFixedOnCellsSummary=containers.Map();
relFixedOnCoverslipsSummary=containers.Map();
kOnCellsSSummary=containers.Map();
kOnCellsErrorSSummary=containers.Map();
kOffCellsSSummary=containers.Map();
kOffCellsErrorSSummary=containers.Map();
kOnCoverslipsSSummary=containers.Map();
kOnCoverslipsErrorSSummary=containers.Map();
kOffCoverslipsSSummary=containers.Map();
kOffCoverslipsErrorSSummary=containers.Map();
boundTimesCellSSummary=containers.Map();
unboundTimesCellSSummary=containers.Map();
boundTimesCoverslipSSummary=containers.Map();
unboundTimesCoverslipSSummary=containers.Map();

figure(16);
clf;
set(gcf,'Position',[56,131,1308,792]);
ax(5)=axes();
hold(ax(5),'on');
title('on cells+coverslips');
xlabel('bound time / s');
ylabel('pdf');

for i=1:size(BEAD_TYPES,2)
    [relFixedOnCells,relFixedOnCoverslips,relFixedOnBoth,...
        totalFixedOnCells,totalFreeOnCells,totalFixedOnCoverslips,totalFreeOnCoverslips]=sas.getGroupRelCounts(BEAD_TYPES{1,i});
    relFixedOnCellsSummary(BEAD_TYPES{1,i})=relFixedOnCells;
    relFixedOnCoverslipsSummary(BEAD_TYPES{1,i})=relFixedOnCoverslips;
    [kOnCellsS,kOnCellsErrorS]=sas.getGroupKOnCellsS(BEAD_TYPES{1,i});
    [kOffCellsS,kOffCellsErrorS]=sas.getGroupKOffCellsS(BEAD_TYPES{1,i});
    [kOnCoverslipsS,kOnCoverslipsErrorS]=sas.getGroupKOnCoverslipsS(BEAD_TYPES{1,i});
    [kOffCoverslipsS,kOffCoverslipsErrorS]=sas.getGroupKOffCoverslipsS(BEAD_TYPES{1,i});
    
    kOnCellsSSummary(BEAD_TYPES{1,i})=kOnCellsS;
    kOnCellsErrorSSummary(BEAD_TYPES{1,i})=kOnCellsErrorS;
    kOffCellsSSummary(BEAD_TYPES{1,i})=kOffCellsS;
    kOffCellsErrorSSummary(BEAD_TYPES{1,i})=kOffCellsErrorS;
    kOnCoverslipsSSummary(BEAD_TYPES{1,i})=kOnCoverslipsS;
    kOnCoverslipsErrorSSummary(BEAD_TYPES{1,i})=kOnCoverslipsErrorS;
    kOffCoverslipsSSummary(BEAD_TYPES{1,i})=kOffCoverslipsS;
    kOffCoverslipsErrorSSummary(BEAD_TYPES{1,i})=kOffCoverslipsErrorS;
    
    boundTimesCellS=sas.getGroupBoundTimesCellsS(BEAD_TYPES{1,i});
    unboundTimesCellS=sas.getGroupUnboundTimesCellsS(BEAD_TYPES{1,i});
    boundTimesCoverslipS=sas.getGroupBoundTimesCoverslipsS(BEAD_TYPES{1,i});
    unboundTimesCoverslipS=sas.getGroupUnboundTimesCoverslipsS(BEAD_TYPES{1,i});
    
    boundTimesCellSSummary(BEAD_TYPES{1,i})=boundTimesCellS;
    unboundTimesCellSSummary(BEAD_TYPES{1,i})=unboundTimesCellS;
%     bksCells=BindingKineticsSim([],[],boundTimesCellS,unboundTimesCellS);
%     [simTCellsS,simBoundCells]=bksCells.getAvgBoundAsFuncOfTime();

    boundTimesCoverslipSSummary(BEAD_TYPES{1,i})=boundTimesCoverslipS;
    unboundTimesCoverslipSSummary(BEAD_TYPES{1,i})=unboundTimesCoverslipS;
    %bksCoverslips=BindingKineticsSim([],[],boundTimesCoverslipS,unboundTimesCoverslipS);
    %[simTCoverslipsS,simBoundCoverslips]=bksCoverslips.getAvgBoundAsFuncOfTime();

    boundTimesBothS=vertcat(repmat(boundTimesCellS,max(totalFixedOnCells),1),repmat(boundTimesCoverslipS,max(totalFixedOnCoverslips),1));
    kOnBoth=kOnCoverslipsS*max(totalFreeOnCoverslips)./(max(totalFreeOnCoverslips+totalFreeOnCells))+...
            kOnCellsS*max(totalFreeOnCells)./max(totalFreeOnCoverslips+totalFreeOnCells);
%     bksBoth=BindingKineticsSim(kOnBoth,[],boundTimesBothS);
%     [simTBothS,simBoundBoth]=bksBoth.getAvgBoundAsFuncOfTime();
    
    tCells=0:length(relFixedOnCells)-1;
    tCoverslips=0:length(relFixedOnCells)-1;
    tBoth=(0:length(relFixedOnBoth)-1)';
    
    plot(ax(1),tCells,...
               relFixedOnCells,...
              'Color',COLORS(i,:),...
              'DisplayName',BEAD_TYPES{1,i},...
              'LineWidth',2);
%     plot(ax(1),tCells,getAlphaOn(kOnCellsS,kOffCellsS,tCells),...
%               'Color',COLORS(i,:),...
%               'HandleVisibility','off');

%     plot(ax(1),simTCellsS,simBoundCells,...
%               'Color',COLORS(i,:),...
%               'HandleVisibility','off');

    plot(ax(2),tCoverslips,...
               relFixedOnCoverslips,...
              'Color',COLORS(i,:),...
              'DisplayName',BEAD_TYPES{1,i},...
              'LineWidth',2);
%     plot(ax(2),tCoverslips,getAlphaOn(kOnCoverslipsS,kOffCoverslipsS,tCoverslips),...
%               'Color',COLORS(i,:),...
%               'HandleVisibility','off');
% 
%     plot(ax(2),simTCoverslipsS,simBoundCoverslips,...
%               'Color',COLORS(i,:),...
%               'HandleVisibility','off');
          
	plot(ax(5),tBoth,...
               relFixedOnBoth,...
              'Color',COLORS(i,:),...
              'DisplayName',BEAD_TYPES{1,i},...
              'LineWidth',2);
          
% 	plot(ax(5),simTBothS,simBoundBoth,...
%               'Color',COLORS(i,:),...
%               'HandleVisibility','off');

    drawnow;
    l.error(BEAD_TYPES{1,i}, '  kOnCellsS: ',kOnCellsS,'  kOffCellsS: ',kOffCellsS,'   kOnCoverslipsS: ',kOnCoverslipsS,'    kOffCoverslipsS: ',kOffCoverslipsS);
end
axes(ax(2));
legend(ax(2),'Box','off','Location','east');


%%  #### SUMMARY PLOTS ####
immobileFractionCellSummary=containers.Map();
immobileFractionCellErrorSummary=containers.Map();
unstickyFractionCellSummary=containers.Map();
unstickyFractionCellErrorSummary=containers.Map();
immobileFractionCoverslipSummary=containers.Map();
immobileFractionCoverslipErrorSummary=containers.Map();
unstickyFractionCoverslipSummary=containers.Map();
unstickyFractionCoverslipErrorSummary=containers.Map();
for i=1:size(BEAD_TYPES,2)
    immobileFractionCell=sum(isinf(boundTimesCellSSummary(BEAD_TYPES{1,i})))/length(boundTimesCellSSummary(BEAD_TYPES{1,i}));
    immobileFractionCellError=sqrt(immobileFractionCell*(1-immobileFractionCell))/sqrt(length(boundTimesCellSSummary(BEAD_TYPES{1,i})));
    immobileFractionCellSummary(BEAD_TYPES{1,i})=immobileFractionCell;
    immobileFractionCellErrorSummary(BEAD_TYPES{1,i})=immobileFractionCellError;
    
    unstickyFractionCell=sum(isinf(unboundTimesCellSSummary(BEAD_TYPES{1,i})))/length(unboundTimesCellSSummary(BEAD_TYPES{1,i}));
    unstickyFractionCellError=sqrt(unstickyFractionCell*(1-unstickyFractionCell))/sqrt(length(unboundTimesCellSSummary(BEAD_TYPES{1,i})));
    unstickyFractionCellSummary(BEAD_TYPES{1,i})=unstickyFractionCell;
    unstickyFractionCellErrorSummary(BEAD_TYPES{1,i})=unstickyFractionCellError;

    immobileFractionCoverslip=sum(isinf(boundTimesCoverslipSSummary(BEAD_TYPES{1,i})))/length(boundTimesCoverslipSSummary(BEAD_TYPES{1,i}));
    immobileFractionCoverslipError=sqrt(immobileFractionCoverslip*(1-immobileFractionCoverslip))/sqrt(length(boundTimesCoverslipSSummary(BEAD_TYPES{1,i})));
    immobileFractionCoverslipSummary(BEAD_TYPES{1,i})=immobileFractionCoverslip;
    immobileFractionCoverslipErrorSummary(BEAD_TYPES{1,i})=immobileFractionCoverslipError;
    
    unstickyFractionCoverslip=sum(isinf(unboundTimesCoverslipSSummary(BEAD_TYPES{1,i})))/length(unboundTimesCoverslipSSummary(BEAD_TYPES{1,i}));
    unstickyFractionCoverslipError=sqrt(unstickyFractionCoverslip*(1-unstickyFractionCoverslip))/sqrt(length(unboundTimesCoverslipSSummary(BEAD_TYPES{1,i})));
    unstickyFractionCoverslipSummary(BEAD_TYPES{1,i})=unstickyFractionCoverslip;
    unstickyFractionCoverslipErrorSummary(BEAD_TYPES{1,i})=unstickyFractionCoverslipError;

    l.error(BEAD_TYPES{1,i},'Cells: kOnCellsS:',   kOnCellsSSummary(BEAD_TYPES{1,i}),...
                            '   kOffCellsS: ',kOffCellsSSummary(BEAD_TYPES{1,i}),...
                            '   kOnCoverslipsS: ',kOnCoverslipsSSummary(BEAD_TYPES{1,i}),...
                            '   kOffCoverslipsS: ',kOffCoverslipsSSummary(BEAD_TYPES{1,i}),...
                            '   Imm% Cell: ', immobileFractionCell,...
                            '   Coverslip: ', immobileFractionCoverslip);
end

figure(20);
clf;
set(gcf,'Position',[209,188,681,778]);
ax(1)=subplot(4,1,1);
toBarPlot(30,BEAD_TYPES,kOnCellsSSummary,kOnCellsErrorSSummary,COLORS,false);
ylabel('k_{on,cells} / s^{-1}');
title('Binding Kinetics (Cells)');
set(ax(1),'YScale','log',...
          'Position',[0.14,0.78,0.84,0.18],...
          'YLim',[1E-3,1E-1]);

ax(2)=subplot(4,1,2);
toBarPlot(ax(2),BEAD_TYPES,kOffCellsSSummary,kOffCellsErrorSSummary,COLORS,false);
ylabel('k_{off,cells} / s^{-1}');
set(ax(2),'YScale','log',...
          'Position',[0.14,0.56,0.84,0.18],...
          'YLim',[1E-4,1E-1]);

ax(3)=subplot(4,1,3);
toBarPlot(ax(3),BEAD_TYPES,immobileFractionCellSummary,immobileFractionCellErrorSummary,COLORS,true);
ylabel('Immobilized Fraction');
set(ax(3),'Position',[0.14,0.34,0.84,0.18],...
          'TickLabelInterpreter','none',...
          'XTickLabel',[],...
          'YLim',[0,1]);
      
ax(4)=subplot(4,1,4);
toBarPlot(ax(4),BEAD_TYPES,unstickyFractionCellSummary,unstickyFractionCellErrorSummary,COLORS,true);
ylabel('Unsticky Fraction');
set(ax(4),'Position',[0.14,0.12,0.84,0.18],...
          'TickLabelInterpreter','none',...
          'YLim',[0,1]);

figure(21);
clf;
set(gcf,'Position',[209,188,681,778]);
ax(1)=subplot(4,1,1);
toBarPlot((1),BEAD_TYPES,kOnCoverslipsSSummary,kOnCoverslipsErrorSSummary,COLORS,false);
ylabel('k_{on,CS} / s^{-1}');
title('Binding Kinetics (Coverslips)');
set(ax(1),'YScale','log',...
          'Position',[0.14,0.78,0.84,0.18],...
          'YLim',[1E-4,1E-1]);

ax(2)=subplot(4,1,2);
toBarPlot(ax(2),BEAD_TYPES,kOffCoverslipsSSummary,kOffCoverslipsErrorSSummary,COLORS,false);
ylabel('k_{off,CS} / s^{-1}');
set(ax(2),'YScale','log',...
          'Position',[0.14,0.56,0.84,0.18],...
          'YLim',[1E-4,1E-1]);

ax(3)=subplot(4,1,3);
toBarPlot(ax(3),BEAD_TYPES,immobileFractionCoverslipSummary,immobileFractionCoverslipErrorSummary,COLORS,true);
ylabel('Immobilized Fraction');
set(ax(3),'Position',[0.14,0.34,0.84,0.18],...
          'XTickLabel',[],... 
          'YLim',[0,1]);
      
ax(4)=subplot(4,1,4);
toBarPlot(ax(4),BEAD_TYPES,unstickyFractionCoverslipSummary,unstickyFractionCoverslipErrorSummary,COLORS,true);
ylabel('Unsticky Fraction');
set(ax(4),'Position',[0.14,0.12,0.84,0.18],...
          'TickLabelInterpreter','none',...
          'YLim',[0,1]);

      %%
% boundTimeEdges=0:20:660;
% figure(23);
% clf;
% set(gcf,'Position',[209,188,681,778]);
% toBoundTimePlot(BEAD_TYPES,boundTimesCellSSummary,boundTimeEdges,COLORS,'t_{bound} / s',true,false);
% annotation(gcf,'textbox',[0 0.92 1 0.075],'VerticalAlignment','middle',...
%     'String','Cells',...
%     'LineStyle','none',...
%     'HorizontalAlignment','center',...
%     'FontSize',12,...
%     'FitBoxToText','off');
% 
% figure(24);
% clf;
% set(gcf,'Position',[209,188,681,778]);
% toBoundTimePlot(BEAD_TYPES,boundTimesCoverslipSSummary,boundTimeEdges,COLORS,'t_{bound} / s',true,false);
% annotation(gcf,'textbox',[0 0.92 1 0.075],'VerticalAlignment','middle',...
%     'String','Coverslips',...
%     'LineStyle','none',...
%     'HorizontalAlignment','center',...
%     'FontSize',12,...
%     'FitBoxToText','off');
% 
% boundTimeEdges=0:20:660;
% figure(25);
% clf;
% set(gcf,'Position',[209,188,681,778]);
% toBoundTimePlot(BEAD_TYPES,unboundTimesCellSSummary,boundTimeEdges,COLORS,'t_{unbound} / s',false,false);
% annotation(gcf,'textbox',[0 0.92 1 0.075],'VerticalAlignment','middle',...
%     'String','Cells',...
%     'LineStyle','none',...
%     'HorizontalAlignment','center',...
%     'FontSize',12,...
%     'FitBoxToText','off');
% 
% boundTimeEdges=0:20:660;
% figure(26);
% clf;
% set(gcf,'Position',[209,188,681,778]);
% toBoundTimePlot(BEAD_TYPES,unboundTimesCoverslipSSummary,boundTimeEdges,COLORS,'t_{unbound} / s',true,true);
% annotation(gcf,'textbox',[0 0.92 1 0.075],'VerticalAlignment','middle',...
%     'String','Coverslips',...
%     'LineStyle','none',...
%     'HorizontalAlignment','center',...
%     'FontSize',12,...
%     'FitBoxToText','off');
% 

% #####  SAVE PLOTS  #####
% if ispc
%     BASE_PATH='E:\tmp\mf\AuswertungBeadvergleichsstudie\BeadvergleichsstudieBindungskinetikPlots\';
% else
%     BASE_PATH='/ep1/home/wolfgang/Auswertung/Mikrofluidik/AuswertungBeadvergleichsstudie/BeadvergleichsstudieBindungskinetikPlots/immobilizedThreshAnalysis/';
% end
% exportgraphics(figure(15), [BASE_PATH,'relFixedCountTimeDep',NAME,'_immobilizedThresholdS_200_end_noShort.pdf'], 'Resolution', 300);
% exportgraphics(figure(20), [BASE_PATH,'BindingRatesCells',NAME,'_immobilizedThresholdS_200_end_noShort.pdf'], 'Resolution', 300);
% exportgraphics(figure(21), [BASE_PATH,'BindingRatesCoverslip',NAME,'_immobilizedThresholdS_200_end_noShort.pdf'], 'Resolution', 300);
% exportgraphics(figure(23), [BASE_PATH,'boundTimesSCellsLog',NAME,'_immobilizedThresholdS_200_end_noShort.pdf'], 'Resolution', 300);
% exportgraphics(figure(24), [BASE_PATH,'boundTimesSCoverslipLog',NAME,'_immobilizedThresholdS_200_end_noShort.pdf'], 'Resolution', 300);
% exportgraphics(figure(25), [BASE_PATH,'unboundTimesSCellsLog',NAME,'_immobilizedThresholdS_200_end_noShort.pdf'], 'Resolution', 300);
% exportgraphics(figure(26), [BASE_PATH,'unboundTimesSCoverslipLog',NAME,'_immobilizedThresholdS_200_end_noShort.pdf'], 'Resolution', 300);
% 
% datetime

%% ##### HELPER FUNCTIONS #####
function toBoundTimePlot(types,boundTimesSummaryS,boundTimeEdges,colors,label,fit,startFitLater)
    set(gcf,'Position',[209,188,681,778]);
    for i=1:size(types,2)
        subplot(size(types,2)+2,1,i+1);
        boundTimesS=boundTimesSummaryS(types{1,i});
        boundTimesS(isinf(boundTimesS))=650;
        h=histogram(boundTimesS,'BinEdges',boundTimeEdges,'Normalization','pdf','FaceColor',colors(i,:),'EdgeColor',colors(i,:)./2,'FaceAlpha',1,'EdgeAlpha',1);
        hold(gca,'on');
        valErrors=sqrt(h.BinCounts)./sum(h.BinCounts)./diff(boundTimeEdges);
        binCenters=diff(boundTimeEdges)/2+boundTimeEdges(1:(end-1));
        erb=errorbar(binCenters,h.Values,valErrors);
        erb.Color = [0 0 0];                            
        erb.LineStyle = 'none';
        
        if fit
            fitter=FitterPlain();
            model=ExponentialModel();
            model.setFixedParameters([NaN,NaN,0]);
            fitter.setModel(model);
            fitter.setErrorAnalysisIterCount(1000);
            if startFitLater
                fitter.setData(binCenters(2:(end-1))',h.Values(2:(end-1))',[],valErrors(2:(end-1))');
            else
                fitter.setData(binCenters(1:(end-1))',h.Values(1:(end-1))',[],valErrors(1:(end-1))');
            end
            fun=fitter.getModelFunWParams();
            param=fitter.getResultParameters();
            paramErrors=fitter.getResultParameterErrors();
            plot(binCenters,fun(binCenters),'Color','k');
        end
        
        ylim([0,0.05]);
        if i~=size(types,2)
            set(gca,'XTick',[]);
        else
            xlabel(label);
        end
        %set(gca,'YTick',0:0.01:0.05);
        set(gca,'YScale','log');
        ylim(gca,[1E-5,1E-1]);
        set(gca,'YTick',[1E-5,1E-4,1E-3,1E-2,1E-1]);
        if i~=1
            set(gca,'YTickLabel',[]);
        else
            ylabel('pdf');
        end
        if fit
            title([types{1,i},', k_off=(',num2str(-1/param(2),'%.3f'),177,num2str(paramErrors(2)./(param(2)^2),'%.3f'),')/s'],'Interpreter','none','Position',[330.8772246733956,0.01,1.4210854715202e-14]);
        else
            title(types{1,i},'Interpreter','none','Position',[330.8772246733956,0.01,1.4210854715202e-14]);
        end
    end
end

function toBarPlot(ax,types,mapCells,mapErrors,colors,showLabels)
    vals=NaN(size(types));
    valErrors=NaN(size(types));
    for i=1:size(types,2)
        vals(1,i)=mapCells(types{1,i});
        if ~isempty(mapErrors)
            valErrors(1,i)=mapErrors(types{1,i});
        end
    end
    hold(gca,'on');
    b=bar(reordercats(categorical(types),types),vals','FaceColor','flat');
    b.CData=colors;
    
    ebp=errorbar(reordercats(categorical(types),types),vals',valErrors');
    ebp.Color = [0 0 0];                            
    ebp.LineStyle = 'none';  
    hold(gca,'off');
    if showLabels
    else
        set(gca,'XTick',[]);
    end
end

function thres=getImobilizedThresholdS()
    thres=200;
end

function alphaOn=getAlphaOn(kOn,kOff,t)
    alphaOn=kOn./(kOn+kOff).*(1-exp(-(kOn+kOff).*t));
end

function saveSedResults(BEAD_TYPES, kOnCellsSSummary, kOnCellsErrorSSummary, kOffCellsSSummary, kOffCellsErrorSSummary, immobileFractionCellSummary, immobileFractionCellErrorSummary,unstickyFractionCellSummary,unstickyFractionCellErrorSummary,kOnCoverslipsSSummary,kOnCoverslipsErrorSSummary,kOffCoverslipsSSummary,kOffCoverslipsErrorSSummary,immobileFractionCoverslipSummary,immobileFractionCoverslipErrorSummary,unstickyFractionCoverslipSummary,unstickyFractionCoverslipErrorSummary)
    CellData = NaN(size(BEAD_TYPES,2),8);
    CoverslipData = NaN(size(BEAD_TYPES,2),8);
    for i=1:size(BEAD_TYPES,2)
        CellData(i,1) = kOnCellsSSummary(BEAD_TYPES{1,i});
        CellData(i,2) = kOnCellsErrorSSummary(BEAD_TYPES{1,i});
        CellData(i,3) = kOffCellsSSummary(BEAD_TYPES{1,i});
        CellData(i,4) = kOffCellsErrorSSummary(BEAD_TYPES{1,i});
        CellData(i,5) = immobileFractionCellSummary(BEAD_TYPES{1,i});
        CellData(i,6) = immobileFractionCellErrorSummary(BEAD_TYPES{1,i});
        CellData(i,7) = unstickyFractionCellSummary(BEAD_TYPES{1,i});
        CellData(i,8) = unstickyFractionCellErrorSummary(BEAD_TYPES{1,i});

        CoverslipData(i,1) = kOnCoverslipsSSummary(BEAD_TYPES{1,i});
        CoverslipData(i,2) = kOnCoverslipsErrorSSummary(BEAD_TYPES{1,i});
        CoverslipData(i,3) = kOffCoverslipsSSummary(BEAD_TYPES{1,i});
        CoverslipData(i,4) = kOffCoverslipsErrorSSummary(BEAD_TYPES{1,i});
        CoverslipData(i,5) = immobileFractionCoverslipSummary(BEAD_TYPES{1,i});
        CoverslipData(i,6) = immobileFractionCoverslipErrorSummary(BEAD_TYPES{1,i});
        CoverslipData(i,7) = unstickyFractionCoverslipSummary(BEAD_TYPES{1,i});
        CoverslipData(i,8) = unstickyFractionCoverslipErrorSummary(BEAD_TYPES{1,i});
    end
end