%% Evaluation of classified results for bead comparison
% SW 26.03.20
function [RESULTS]=runMFevaluationTimeDependent()

timeAfterFlush = 30;

% BEADTYPES = {'BeadvergleihcsstudiePolyscienceAMIN',...
%     'BeadvergleihcsstudiePolyscienceCOOH',...
%     'BeadvergleihcsstudiemicromodCOOH',...
%     'BeadvergleihcsstudiePolysciencePLAIN',...
%     'BeadvergleihcsstudiemicromodPLAIN',...
%     'BeadvergleihcsstudiemicroparticlesGmbH'...
%     'BeadvergleihcsstudieKisker',...
%     'BeadvergleihcsstudieSpherotech',...
%     'BeadvergleihcsstudieThermoScientific',...
%     'Tianjin',...
%     'Phosphorex',...
%     };

% BEADTYPES = {'BeadvergleihcsstudiePolyscienceCOOH',... %Sortiert nach abs(Zetapotential)
%     'BeadvergleihcsstudieSpherotech',...
%     'BeadvergleihcsstudiePolysciencePLAIN',...
%     'BeadvergleihcsstudiemicromodCOOH',...
%     'Tianjin',...
%     'BeadvergleihcsstudiePolyscienceAMIN'...
%     'BeadvergleihcsstudieThermoScientific',...
%     'Phosphorex',...
%     'BeadvergleihcsstudiemicroparticlesGmbH',...
%     'BeadvergleihcsstudieKisker',...
%     'BeadvergleihcsstudiemicromodPLAIN',...
%     };
% 
% BEADTYPES={'polyscienceCOOH(.+)_0min',...
%     'polyscienceCOOH(.+)_40min',...
%     'polyscienceCOOH(.+)_80min',...
%     'micromodCOOH(.+)_0min',...
%     'micromodCOOH(.+)_40min',...
%     'micromodCOOH(.+)_80min',...
%     'spherotechNH2(.+)_0min',...
%     'spherotechNH2(.+)_40min',...
%     'spherotechNH2(.+)_80min',...
%     'micromodNH2(.+)_0min',...
%     'micromodNH2(.+)_40min',...
%     'micromodNH2(.+)_80min',...
%     'polyscienceNH2(.+)_0min',...
%     'polyscienceNH2(.+)_40min',...
%     'polyscienceNH2(.+)_80min',...
%     'micromodNR3(.+)_0min',...
%     'micromodNR3(.+)_40min',...
%     'micromodNR3(.+)_80min'};

% BEADTYPES={
%     'micromodNH2_50pN(.+)',...
%     'micromodNH2_100pN(.+)',...
%     'micromodNH2_150pN(.+)',...
%     'micromodNH2_200pN(.+)',...
%     'micromodNH2_250pN(.+)',...
%     'micromodNR3_100pN(.+)',...
%     'micromodNR3_150pN(.+)',...
%     'micromodNR3_200pN(.+)',...
%     'micromodNR3_300pN(.+)',...
%     'micromodNR3_400pN(.+)',...
%     'micromodNR3_500pN(.+)',...
%     'micromodNR3_600pN(.+)'};
% 
% RESULTS{1,1} = [];
% 
% BEADTYPES={
%     'polyscience(.+)200(.+)',...
%     'polyscience(.+)250(.+)',...
%     'polyscience(.+)300(.+)',...
%     'polyscience(.+)400(.+)'
%     };
% 
% RESULTS{1,1} = [];
% %RESULTSAtt{11,3} = [];
% 
% ZETAPOT = {-75.5,-75.5,-75.5,...
%             -48.7,-48.7,-48.7,...
%             -15.7,-15.7,-15.7,...
%             -5.3,-5.3,-5.3,...
%             53.6,53.6,53.6,...
%             100,100,100}; %Selbe Sortierung wie Beadtypes, Werte für NR3+ willkürlich!

%RESULTSAtt{11,3} = [];

% ZETAPOT = { -75.5,-75.5,-75.5,-75.5}; %Selbe Sortierung wie Beadtypes, Werte für NR3+ willkürlich!

BEADTYPES={'polyscienceCOOH(.+)',...
    'micromodCOOH(.+)',...
    'spherotechNH2(.+)',...
    'micromodNH2(.+)',...
    'polyscienceNH2(.+)',...
    'micromodNR3(.+)'};
% 
% RESULTS{1,1} = [];
% 
% BEADTYPES={'MMC','MMplain'};
% NAME='';

ZETAPOT = {-75.5,...
            -48.7,...
            -15.7,...
            -5.3,...
            53.6,...
            -0.39};  %old zeta-potentials for 50pN

% ZETAPOT = {-57.6,...
%             -48.7,...
%             -15.7,...
%             -5.3,...
%             -7.0,...
%             -0.39};  %new zeta-potentials for 400pN
% 
% ZETAPOT = {-48.7,...
%             -7.0};  %new zeta-potentials for 400pN


%micromod Plain


for i = 1:length(BEADTYPES)
    
    FILENAMES = getFilesByRegexName('/ep1/home/matteo/Mikrofluidik/Messdaten/50pN',false,strcat('(.+)(?=', BEADTYPES{i}, ')(.+)(?<=(_result.*)).mat$'))';

    
    resAttached0 = [];
    resNotAttached0 = [];
    
    resAttached40 = [];
    resNotAttached40 = [];

    resAttached80 = [];
    resNotAttached80 = [];
    
    for k = 1:length(FILENAMES)
        
        %FILENAMES{k}
        l=load(FILENAMES{k});
        res = mfResults(l.cctlResult,5,'dummypfad');
        if res.tryClassificationSucces()
            %force=res.force(res.getStartFrameFlush());
            if contains(FILENAMES{k},'50pN')
                nas = res.getNumberAttachedAfterSedimentation();                            % No. of beads attatched to cells directly after sedimentation
                nnas = res.getNumberNotAttachedAfterSedimentation();                        % No. of beads NOT attatched to cells directly after sedimentation
                ns = nas+nnas;                                                              % No. of total beads directly after sedimentation
                rna=res.getRelNumberAttachedAtTimepointAfterFlush(timeAfterFlush);          % fractions of beads attatched to cells @taf irt. beads attatched to cells directly after sedimentation
                rnna=res.getRelNumberNotAttachedAtTimepointAfterFlush(timeAfterFlush);      % fractions of beads NOT attatched to cells @taf irt. beads attatched NOT to cells directly after sedimentation
                resAttached0 = [resAttached0; rna,nas,ns];                                  % rel. no. attatched @taf,   no. attatched after sed,   total no. after sed     fa. measurements of ONE bead type
                resNotAttached0 = [resNotAttached0;rnna,nnas,ns];                           % rel. no. NOT attatched @taf,   no. NOT attatched after sed,   total no. after sed     fa. measurements of ONE bead type
            % OPTIONAL 1: uncomment if seperation of incubation times
            %           needed; change '50pN' in first if to '50pN_0'
            % elseif contains(FILENAMES{k},'_40min')
            %     nas = res.getNumberAttachedAfterSedimentation();
            %     nnas = res.getNumberNotAttachedAfterSedimentation();
            %     ns = nas+nnas;
            %     rna=res.getRelNumberAttachedAtTimepointAfterFlush(timeAfterFlush);
            %     rnna=res.getRelNumberNotAttachedAtTimepointAfterFlush(timeAfterFlush);
            %     resAttached40 = [resAttached40; rna,nas,ns];
            %     resNotAttached40 = [resNotAttached40;rnna,nnas,ns];
            % elseif contains(FILENAMES{k},'_80min')
            %     nas = res.getNumberAttachedAfterSedimentation();
            %     nnas = res.getNumberNotAttachedAfterSedimentation();
            %     ns = nas+nnas;
            %     rna=res.getRelNumberAttachedAtTimepointAfterFlush(timeAfterFlush);
            %     rnna=res.getRelNumberNotAttachedAtTimepointAfterFlush(timeAfterFlush);
            %     resAttached80 = [resAttached80; rna,nas,ns];
            %     resNotAttached80 = [resNotAttached80;rnna,nnas,ns];
            % END OPTIONAL 1
            else
                err = strcat('No time specified in: ',FILENAMES{k});
                warning(err);
            end
            
            
        else
            warning(strcat('Unsuccesful calssification in ',FILENAMES{k}));
        end
        
    end
    
    neffA0 = (sum(resAttached0(:,2)))^2/sum((resAttached0(:,2)).^2);                    % effective sample size of attatched beads (cf. BA thesis Sarah Spreng p.29)                     
    neffNa0 = (sum(resNotAttached0(:,2)))^2/sum((resNotAttached0(:,2)).^2);             % effective sample size of NOT attatched beads (cf. BA thesis Sarah Spreng p.29)
    
    resAtt0 = [nanwmean(resAttached0(:,1),resAttached0(:,2)),sqrt(nanvar(resAttached0(:,1),resAttached0(:,2)))/sqrt(neffA0)];       % mean fraction of beads att to cells @taf irt. beads att to cells after sed (weighted w\ no. beads att to cells after sed)
    nAtt0 = sum(resAttached0(:,2));                                                     % total no. attatched after sedimentation within one group
    resNAtt0 = [nanwmean(resNotAttached0(:,1),resNotAttached0(:,2)),sqrt(nanvar(resNotAttached0(:,1),resNotAttached0(:,2)))/sqrt(neffNa0)];         % mean fraction of beads NOT attatched to cells @taf irt. beads NOT att to cells after sed (weighted w\ no. beads NOT att to cells after sed)
    nnAtt0 = sum(resNotAttached0(:,2));                                                 % total no. NOT attatched after sedimentation within one group
    numberspcAtt0 = [nanmean(resAttached0(:,2)),nanstd(resAttached0(:,2))/sqrt(neffA0)];                % mean & std of abs no. beads att to cells after sed
    numberspcnAtt0 = [nanmean(resNotAttached0(:,2)),nanstd(resNotAttached0(:,2))/sqrt(neffNa0)];        % mean & std of abs no. beads NOT att to cells after sed    
    numberspc0 = [nanmean(resAttached0(:,3)),nanstd(resAttached0(:,3))/sqrt(mean([neffNa0,neffA0]))];   % mean & std of total no. beads after sed       
    
    
    
    % neffA40 = (sum(resAttached40(:,2)))^2/sum((resAttached40(:,2)).^2);
    % neffNa40 = (sum(resNotAttached40(:,2)))^2/sum((resNotAttached40(:,2)).^2);
    % 
    % resAtt40 = [nanwmean(resAttached40(:,1),resAttached40(:,2)),sqrt(nanvar(resAttached40(:,1),resAttached40(:,2)))/sqrt(neffA40)];
    % nAtt40 = sum(resAttached40(:,2));
    % resNAtt40 = [nanwmean(resNotAttached40(:,1),resNotAttached40(:,2)),sqrt(nanvar(resNotAttached40(:,1),resNotAttached40(:,2)))/sqrt(neffNa40)];
    % nnAtt40 = sum(resNotAttached40(:,2));
    % numberspcAtt40 = [nanmean(resAttached40(:,2)),nanstd(resAttached40(:,2))/sqrt(3)];
    % numberspcnAtt40 = [nanmean(resNotAttached40(:,2)),nanstd(resNotAttached40(:,2))/sqrt(3)];
    % numberspc40 = [nanmean(resAttached40(:,3)),nanstd(resAttached40(:,3))/sqrt(3)];
    % 
    % 
    % 
    % 
    % neffA80 = (sum(resAttached80(:,2)))^2/sum((resAttached80(:,2)).^2);
    % neffNa80 = (sum(resNotAttached80(:,2)))^2/sum((resNotAttached80(:,2)).^2);
    % 
    % resAtt80 = [nanwmean(resAttached80(:,1),resAttached80(:,2)),sqrt(nanvar(resAttached80(:,1),resAttached80(:,2)))/sqrt(neffA0)];
    % nAtt80 = sum(resAttached80(:,2));
    % resNAtt80 = [nanwmean(resNotAttached80(:,1),resNotAttached80(:,2)),sqrt(nanvar(resNotAttached80(:,1),resNotAttached80(:,2)))/sqrt(neffNa0)];
    % nnAtt80 = sum(resNotAttached80(:,2));
    % numberspcAtt80 = [nanmean(resAttached80(:,2)),nanstd(resAttached80(:,2))/sqrt(3)];
    % numberspcnAtt80 = [nanmean(resNotAttached80(:,2)),nanstd(resNotAttached80(:,2))/sqrt(3)];
    % numberspc80 = [nanmean(resAttached80(:,3)),nanstd(resAttached80(:,3))/sqrt(3)];
    
    % RESULTSAtt{i} = resAttached;
    RESULTS{i,1} = [resAtt0,nAtt0,numberspcAtt0,numberspc0,neffA0;resNAtt0,nnAtt0,numberspcnAtt0,numberspc0,neffNa0];
    % RESULTS{i,2} = [resAtt40,nAtt40,numberspcAtt40,numberspc40,neffA40;resNAtt40,nnAtt40,numberspcnAtt40,numberspc40,neffNa40];
    % RESULTS{i,3} = [resAtt80,nAtt80,numberspcAtt80,numberspc80,neffA80;resNAtt80,nnAtt80,numberspcnAtt80,numberspc80,neffNa80];
    
end

% for i=1:length(BEADTYPES)
%     BEADTYPES{i} = erase(BEADTYPES{i},'Beadvergleihcsstudie');  
% end

RESULTS = [RESULTS,BEADTYPES',ZETAPOT'];

end






% att=zeros(18,2);
% natt=zeros(18,2);
% numberstot=zeros(18,2);
% numberspc=zeros(18,2);

% attsm = zeros(9,18);
% nattsm = zeros(9,18);
% for i = 1:18
%     att(i,1) = RESULTS{i}(1,1);
%     att(i,2) = RESULTS{i}(1,2);
%     natt(i,1) = RESULTS{i}(2,1);
%     natt(i,2) = RESULTS{i}(2,2);
%     numberstot(i,1) = RESULTS{i}(1,3);
%     numberstot(i,2) = RESULTS{i}(2,3);
%     numberspc(i,1) = RESULTS{i}(1,4)+RESULTS{i}(2,4);
%     numberspc(i,2) = sqrt((RESULTS{i}(1,5))^2+(RESULTS{i}(2,5))^2);
%     % attsm(1:length(RESULTSAtt{i}(:,1)),i) = RESULTSAtt{i}(:,1);
%     % nattsm(1:length(RESULTSAtt{i}(:,2)),i) = RESULTSAtt{i}(:,2);
% end
% 
% %figure Attached
% figure('Position',[100 100 1200 800],'DefaultAxesFontSize',18);
% b = bar(1:18,att(:,1));
% hold on;
% er = errorbar(1:18,att(:,1),att(:,2));
% er.Color = [0 0 0];
% er.LineStyle='none';
% b.LineWidth=2;
% b.FaceColor = [0.75 0.75 0.75];
% er.LineWidth=2;
% 
% xticks([1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18]);
% xticklabels({'PY COOH 0min',...
%             'PY COOH 40min',...
%             'PY COOH 80min',...
%             'MM COOH 0min',...
%             'MM COOH 40min',...
%             'MM COOH 80min',...
%             'ST NH2 0min',...
%             'ST NH2 40min',...
%             'ST NH2 80min',...
%             'MM NH2 0min',...
%             'MM NH2 40min',...
%             'MM NH2 80min',...
%             'PY NH2 0min',...
%             'PY NH2 40min',...
%             'PY NH2 80min',...
%             'MM NR3+ 0min',...
%             'MM NR3+ 40min',...
%             'MM NR3+ 80min'});
% xtickangle(45);
% 
% title('Rel. Number of Beads attached to cells after 30s, F=50pN');
% 
% set(gca,'LineWidth',2);
% box on;
% 
% %figure einzelmessungen Attached
% figure('Position',[100 100 1200 800],'DefaultAxesFontSize',18);
% b = bar(attsm','LineWidth',2);
% hold on;
% set(b,{'FaceColor'},{[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75]});
% 
% xticks([1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18]);
% xticklabels({'PY COOH 0min',...
%             'PY COOH 40min',...
%             'PY COOH 80min',...
%             'MM COOH 0min',...
%             'MM COOH 40min',...
%             'MM COOH 80min',...
%             'ST NH2 0min',...
%             'ST NH2 40min',...
%             'ST NH2 80min',...
%             'MM NH2 0min',...
%             'MM NH2 40min',...
%             'MM NH2 80min',...
%             'PY NH2 0min',...
%             'PY NH2 40min',...
%             'PY NH2 80min',...
%             'MM NR3+ 0min',...
%             'MM NR3+ 40min',...
%             'MM NR3+ 80min'});
% xtickangle(45);
% 
% title('Rel. Number of Beads attached, for each single measurement');
% 
% set(gca,'LineWidth',2);
% box on;
% 
% %figure einzelmessungen Anzahl
% figure('Position',[100 100 1200 800],'DefaultAxesFontSize',18);
% b = bar(nattsm','LineWidth',2);
% hold on;
% set(b,{'FaceColor'},{[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75];[0.75 0.75 0.75]});
% 
% xticks([1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18]);
% xticklabels({'micromod Plain', 'micromod COOH', 'Polyscience Plain', 'Polyscience COOH', 'Polyscience NH_2',...
%     'Kisker Plain', 'Phosphorex Plain', 'Spherotech Plain', 'Tianjin Plain',...
%     'Thermo Scientific Plain', 'microparticles GmbH Plain'});
% xtickangle(45);
% 
% title('Number of  Beads attached before flush, for each single measurement');
% 
% set(gca,'LineWidth',2);
% box on;
% 
% %figure not attached
% figure('Position',[100 100 1200 800],'DefaultAxesFontSize',18);
% b = bar(1:11,natt(:,1));
% hold on;
% er = errorbar(1:11,natt(:,1),natt(:,2));
% er.Color = [0 0 0];
% er.LineStyle='none';
% b.LineWidth=2;
% b.FaceColor = [0.75 0.75 0.75];
% er.LineWidth=2;
% 
% xticks([1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18]);
% xticklabels({'PY COOH 0min',...
%             'PY COOH 40min',...
%             'PY COOH 80min',...
%             'MM COOH 0min',...
%             'MM COOH 40min',...
%             'MM COOH 80min',...
%             'ST NH2 0min',...
%             'ST NH2 40min',...
%             'ST NH2 80min',...
%             'MM NH2 0min',...
%             'MM NH2 40min',...
%             'MM NH2 80min',...
%             'PY NH2 0min',...
%             'PY NH2 40min',...
%             'PY NH2 80min',...
%             'MM NR3+ 0min',...
%             'MM NR3+ 40min',...
%             'MM NR3+ 80min'});
% xtickangle(45);
% 
% title('Rel. Number of Beads attached to coverslip after 30s, F=50pN');
% 
% set(gca,'LineWidth',2);
% box on;
% 
% %figure numbers
% figure('Position',[100 100 1200 800],'DefaultAxesFontSize',18);
% b = bar(1:11,numberstot,'stacked','LineWidth',2);
% set(b,{'FaceColor'},{[0.5 0.5 0.5];[0.75 0.75 0.75]});
% legend({'on cells','on coverslip'},'Location','northwest');
% hold on;
% %er = errorbar(1:11,natt(:,1),natt(:,2));
% %er.Color = [0 0 0];
% %er.LineStyle='none';
% %b.LineWidth={2,2};
% %b.FaceColor = [0.75 0.75 0.75];
% %er.LineWidth=2;
% 
% xticks([1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18]);
% xticklabels({'PY COOH 0min',...
%             'PY COOH 40min',...
%             'PY COOH 80min',...
%             'MM COOH 0min',...
%             'MM COOH 40min',...
%             'MM COOH 80min',...
%             'ST NH2 0min',...
%             'ST NH2 40min',...
%             'ST NH2 80min',...
%             'MM NH2 0min',...
%             'MM NH2 40min',...
%             'MM NH2 80min',...
%             'PY NH2 0min',...
%             'PY NH2 40min',...
%             'PY NH2 80min',...
%             'MM NR3+ 0min',...
%             'MM NR3+ 40min',...
%             'MM NR3+ 80min'});
% xtickangle(45);
% 
% title('Total number of beads evaluated');
% 
% set(gca,'LineWidth',2);
% box on;
% 
% %figure numbers on CS
% figure('Position',[100 100 1200 800],'DefaultAxesFontSize',18);
% b = bar(1:11,numberspc(:,1));
% hold on;
% er = errorbar(1:11,numberspc(:,1),numberspc(:,2));
% er.Color = [0 0 0];
% er.LineStyle='none';
% b.LineWidth=2;
% b.FaceColor = [0.75 0.75 0.75];
% er.LineWidth=2;
% 
% xticks([1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18]);
% xticklabels({'PY COOH 0min',...
%             'PY COOH 40min',...
%             'PY COOH 80min',...
%             'MM COOH 0min',...
%             'MM COOH 40min',...
%             'MM COOH 80min',...
%             'ST NH2 0min',...
%             'ST NH2 40min',...
%             'ST NH2 80min',...
%             'MM NH2 0min',...
%             'MM NH2 40min',...
%             'MM NH2 80min',...
%             'PY NH2 0min',...
%             'PY NH2 40min',...
%             'PY NH2 80min',...
%             'MM NR3+ 0min',...
%             'MM NR3+ 40min',...
%             'MM NR3+ 80min'});
% xtickangle(45);
% 
% title('Average number of beads per measurement');
% 
% set(gca,'LineWidth',2);
% box on;