classdef CCTLControlPanelCamera < CCTLControlPanelManaged 
    methods(Access=public)        
        function title = getTitle(~)
            title='Camera';
        end
        
        function names = getNames(~)
             names={'CameraClass',...
                    'ExposureTime/s',...
                    'Pixelsize/um',...
                    'Binning (X*X)/(px*px)',...
                    'UpdateImageInRunMode',...
                    'ShowHistogram',...
                    'HistogramSteps',...
                    'ShowOverilluminationWarning',...
                    'Set ROI',...
                    'Reset ROI'};
        end
    end
    
    methods(Access=protected)
        function types = getDisplayTypes(~)
             types={CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL};
        end
        
        function strings=getStartStrings(~)
               strings={'',...
                        0.005,...
                        0.2146,...
                        2,...
                        '',...
                        '',...
                        150,...
                        '',...
                        '',...
                        ''};
        end
        
        function values=getStartValues(~)
            values={NaN,...
                    NaN,...
                    NaN,...
                    NaN,...
                    1,...
                    0,...
                    NaN,...
                    0,...
                    0,...
                    0};
        end
        
        function styles=getStyles(~)
             styles={'edit',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'checkbox',...
                     'checkbox',...
                     'edit',...
                     'checkbox',...
                     'pushbutton',...
                     'pushbutton'};
        end
        
        function tt=getTooltips(~)
              tt={'The loaded camera model class',...
                  'Camera exposure time /s',...
                  'The pixelsize of the camera/objective combination',...
                  'Camera binning',...
                  'Turns off updating the analysis figure in live mode (images are still saved) for better performance.',...
                  'Turns off the histogram',...
                  'The number of bins in the image histogram.',...
                  '',...
                  'Set a new Camera ROI',...
                  'Reset the Camera ROI to the maximum FOV'};
        end
        
        function postEnableInput(obj,~)
            set(obj.getUiControl('UpdateImageInRunMode'),'Enable','On');
            set(obj.getUiControl('ShowHistogram'),'Enable','On');
            set(obj.getUiControl('ShowOverilluminationWarning'),'Enable','On');
            set(obj.getUiControl('HistogramSteps'),'Enable','On');
            set(obj.getUiControl('CameraClass'),'Enable','Off');
        end
        
        function restore=restoreStatusOnLoad(~)
            restore={false,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     false,...
                     false};
        end
    end
end

