classdef CCTLControlPanelMicrofluidics < CCTLControlPanelManaged
    properties(Access=private)
        stageInitialized=false;
    end
    
    methods(Access=public)
        function obj=CCTLControlPanelMicrofluidics()
            set(obj.getUiControl('Stop Pumping'),'BackgroundColor',[1 0.3 0.3]);
        end
        
        
        function enableInput(obj, ~)
            if obj.stageInitialized
                enableInput@CCTLControlPanel(obj,'on')
            elseif ~obj.stageInitialized
                enableInput@CCTLControlPanel(obj,'off')
            end
            % button is always on/off
            set(obj.getUiControl('Init Stage'),'Enable','on');
            set(obj.getUiControl('Channel Height Profile/mm'),'Enable','inactive');
        end
        
        function result=doAction(obj, actionCommand, varargin)
            switch actionCommand
                case 'microfluidicsStageInitialized'
                    obj.stageInitialized=true;
                    obj.enableInput('on');
                    result=[];
                case 'setHeightProfileWarning'
                    obj.setHeightProfileWarning(varargin{1});
                    result=[];
                otherwise
                    result=doAction@CCTLControlPanel(obj,actionCommand,varargin);
            end
        end
        
        function title = getTitle(~)
            title='Microfluidics';
        end
        
        function names = getNames(~)
             names={'Init Stage',...
                    'Channel Width/mm',...
                    'Channel Width Error/mm',...
                    'Channel Height/mm',...
                    'Channel Height Error/mm',...
                    'Channel Height Profile/mm',...
                    'ChannelHeightProfileValues/mm',...
                    'ShowHeightProfileFit',...
                    'Channel Length/mm',...
                    'y Error/um',...
                    'z Error/um',...
                    'Viscosity/PaS',...%10
                    'Syringe Radius/mm',...
                    'Syringe Radius Error/mm',...
                    'ParticleRadius/um',...
                    'Flow Rate/ul/s',...
                    'ForceOnParticle/pN',...
                    'Pressure Drop Sample/Bar',...%15
                    'ShowFlowProfile',...
                    'PistonVelocity/mm/s',...
                    'PistonVelocity Error/mm/s',...
                    'Position/mm',...
                    'Set Syringe Full',...%20
                    'Set Syringe Empty',...
                    'Syringe Full Position/mm',...
                    'Syringe Empty Position/mm',...
                    'Go To Syringe Full Position',...
                    'Go To Syringe Empty Position',...%25
                    'Continuous Flow',...
                    'Keyboard Control',...
                    'Stop Pumping'};
        end
    end
    
    methods(Access=protected)
        function lineCounts=getItemLineCounts(obj)
            lineCounts=obj.getItemLineCounts@CCTLControlPanelManaged();
            lineCounts(7,1)=9; % see obj.postAddAll()
        end
        
        function types = getDisplayTypes(~)
             types={CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL,...
                    CCTLViewerControlDisplayType.HALF_WIDTH_CONTROL};
        end
        
        function strings=getStartStrings(~)
               strings={'',...
                        '1.01481',...
                        '0.01',...
                        '0.105081',...
                        '0.005',...
                        '',...
                        '',...
                        '',...
                        '19.075',...
                        '5',...
                        '5',...
                        '0.0007',...
                        '6.135',...
                        '0.5',...
                        '1.5',...
                        '1',...
                        '1',...
                        '',...
                        '',...
                        '',...
                        '0.0001',...
                        '',...
                        '',...
                        '',...
                        '',...
                        '',...
                        '',...
                        '',...
                        '',...
                        '',...
                        ''};
        end
        
        function values=getStartValues(~)
            values={0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0,...
                    0};
        end
        
        function styles=getStyles(~)
             styles={'pushbutton',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'text',...
                     'edit',...
                     'pushbutton',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'edit',...
                     'text',...
                     'pushbutton',...
                     'text',...
                     'edit',...
                     'edit',...
                     'pushbutton',...
                     'pushbutton',...
                     'edit',...
                     'edit',...
                     'pushbutton',...
                     'pushbutton',...
                     'togglebutton',...
                     'togglebutton',...
                     'pushbutton'};
        end
        
        function tt=getTooltips(~)
               tt={'Initializes the stage.',...
                   'The width of the channel.',...
                   '',...
                   'The heigth of the channel at the current position.',...
                   '',...
                   '',...
                   sprintf(['The height profile of the cannel h(y) (y is 0 in the middle of the channel):\n',...
                             'Y1 / mm,h1 / mm\n',...
                             'Y2 / mm,h2 / mm\n',...
                             'Y3 / mm,h3 / mm\n',...
                             '...']),...
                   '',...
                   'The length of the channel.',...
                   'How accurately a position can be measured in y-direction (backwards in the lab)',...
                   'How accurately a position can be measured in z-direction (upwards in the lab)',...
                   'The viscosity of the liquid.',...
                   'The radius of the used syringe.',...
                   '',...
                   'The radius of the particle used for force calculation.',...
                   'The flow rate in the channel given by the stage velocity and the syringe radius.',...
                   'The translational force acting on a particle near the surface (Model by Lehman et al. Gekle Group).',...
                   'The pressure drop in the channel accoring to the other settings.',...
                   'Displays the flow profile along with the errors.',...
                   'The piston (stage) velocity.',...
                   'The error of the piston (stage) velocity.',...
                   'The current stage position.',...
                   'Sets the current stage position as the syringe full position.',...
                   'Sets the current stage position as the syringe empty position.',...
                   'The stage position at which the syringe is full.',...
                   'The stage position at which the syringe is empty.',...
                   'Moves to the syringe full position.',...
                   'Moves to the syringe empty position.',...
                   'The stage moves back and forth between the syringe full and empty position.',...
                   'Enables keyboard control.',...
                   'Stops the pumping.'};
        end
        
        function restore=restoreStatusOnLoad(~)
            restore={false,...
                     true,...
                     true,...
                     true,...
                     true,...
                     false,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     false,...
                     false,...
                     false,...
                     true,...
                     false,...
                     false,...
                     false,...
                     true,...
                     true,...
                     false,...
                     false,...
                     false,...
                     false,...
                     false};
        end
        
        function setHeightProfileWarning(obj,warnStatus)
            if warnStatus
                set(obj.getUiControl('ChannelHeightProfileValues/mm'),'BackgroundColor',[.8 .2 .2]);
            else
                set(obj.getUiControl('ChannelHeightProfileValues/mm'),'BackgroundColor',[.94 .94 .94]);
            end
        end
        
        function postEnableInput(~,~)
        end
        
        function postAddAll(obj)
            uicont=obj.getUiControl('ChannelHeightProfileValues/mm');
            set(uicont,'String','');
            set(uicont,'Max',2); % enables multiline input
            set(uicont,'HorizontalAlignment','left');
        end
    end
end

