classdef CCTLControlPanelFocusMeasure < CCTLControlPanelManaged    
    methods(Access=public)
        function title = getTitle(~)
            title='Focus Measure';
        end
        function names = getNames(~)
            names={'FocusMeasureCalculation',...
                   'FocusMeasureCrop/px',...
                   'FocusMeasureLowTh',...
                   'FocusMeasureHighTh',...
                   'ShowFocusMeasureMaskInLiveMode',...
                   'FocusMeasure'};
        end
    end
    
    methods(Access=protected)        
        function types = getDisplayTypes(~)
            types={CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                CCTLViewerControlDisplayType.TXT_AND_CONTROL,...
                CCTLViewerControlDisplayType.TXT_AND_CONTROL};
        end
        
        function strings=getStartStrings(~)
            strings={'',...
                '200',...
                '0',...
                'inf',...
                '',...
                ''};
        end
        
        function values=getStartValues(~)
            values={1,...
                NaN,...
                NaN,...
                NaN,...
                0,...
                NaN};
        end
        
        function styles=getStyles(~)
            styles={'checkbox',...
                'edit',...
                'edit',...
                'edit',...
                'checkbox',...
                'edit'};
        end
        
        function tt=getTooltips(~)
            tt={'TODO',...
                'TODO',...
                'TODO',...
                'TODO',...
                'TODO',...
                'TODO'};
        end
        
        function restore=restoreStatusOnLoad(~)
            restore={true,...
                     true,...
                     true,...
                     true,...
                     true,...
                     false};
        end
        
        function postEnableInput(obj,active)
            if strcmp(active,'on')
                obj.calcCallback()
            elseif strcmp(active,'off')
                set(obj.getUiControl('FocusMeasureLowTh'),'Enable','on');
                set(obj.getUiControl('FocusMeasureHighTh'),'Enable','on');
                set(obj.getUiControl('ShowFocusMeasureMaskInLiveMode'),'Enable','on');
            end
            % FocusMeasure output are always off
            set(obj.getUiControl('FocusMeasure'),'Enable','off');
        end
        
        function postAddAll(obj)
             set(obj.getUiControl('FocusMeasureCalculation'),'Callback',@obj.calcCallback);
        end
    end
    
    methods(Access=private)
        function calcCallback(obj,~,~)
            if get(obj.getUiControl('FocusMeasureCalculation'),'Value')
                set(obj.getUiControl('FocusMeasureCrop/px'), 'Enable','On');
                set(obj.getUiControl('FocusMeasureLowTh'), 'Enable','On');
                set(obj.getUiControl('FocusMeasureHighTh'), 'Enable','On');
                set(obj.getUiControl('ShowFocusMeasureMaskInLiveMode'), 'Enable','On');
            else
                set(obj.getUiControl('FocusMeasureCrop/px'), 'Enable','Off');
                set(obj.getUiControl('FocusMeasureLowTh'), 'Enable','Off');
                set(obj.getUiControl('FocusMeasureHighTh'), 'Enable','Off');
                set(obj.getUiControl('ShowFocusMeasureMaskInLiveMode'), 'Enable','Off');
            end
            set(obj.getUiControl('FocusMeasure'),'Enable','off');
        end
    end
end